### ISSUE TITLE
Text Add behaves unpredictable when going back.

### ISSUE THREAD

**Issue by goldenxp** [Kirilllive/tuesday-js#12]
If you click the story back button, text-add adds to the current window before going to the previous scene.
See the following novel.
[new_novel.json.txt](https://github.com/Kirilllive/tuesday-js/files/6689217/new_novel.json.txt)

**Comment by goldenxp** [comment]
I'm also encountering a _repeating_ bug with Text Adds. If you go back and forth multiple times, you append the same string over and over.

**Comment by Kirilllive** [comment]
Hello! thanks for testing, unfortunately I am aware of this problem and at the moment do not know how to properly solve it. 

the problem is that it is not known which replica was originally before the additions. flipping through all the dialogues and forming a replica is a very big operation.

for now, I would recommend avoiding text add at the end of the scene.
